### ISSUE TITLE
Wrong list object type

### ISSUE THREAD

**Issue by akrasnoshchok** [onfido/onfido-java#18]
https://github.com/onfido/onfido-java/blob/f95f2a1c8cf28380165a0cb759dffb62fe85154a/onfido-java/src/main/models/report.json#L52

Documentation:
https://documentation.onfido.com/#document-report

>"documents": [
>    {
>      "id": "<DOCUMENT_ID>"
>    }
>  ]

"documents" property should contain list of objects with id inside, but not a list of strings.

**Comment by ciaran16** [comment]
v1.0.1 is now on Maven Central with your fix - thanks again @akrasnoshchok
