### ISSUE TITLE
Ability to set document_ids

### ISSUE THREAD

**Issue by formerllamafarmer** [onfido/onfido-java#32]
The v3 API is documented to continue the v2 API's ability to specify which of the uploaded documents will be used in performing a check:

https://developers.onfido.com/guide/api-v2-to-v3-migration-guide#document-ids-in-the-document-report

However there is not an option to set those using the java client.  Expecting to be able to do something like,

`Check.request().applicantId(applicantId).reportNames(reportNames).documentIds(documentIds)`

**Comment by ciaran16** [comment]
This was fixed in v1.3.1, apologies for not closing sooner.
