### ISSUE TITLE
After setting document_ids, an error comes: 422 Document(s) don't belong to applicant.

### ISSUE THREAD

**Issue by warrioru** [onfido/onfido-java#34]
I am creating a check with the applicant id received by creating an onfido applicant. Afterwards, I create a check using this id and the new document_ids field released in v1.3.1 and I always receive the error with code 422, **Document(s) don't belong to applicant.**

**Comment by ciaran16** [comment]
Hi @warrioru, are you setting the applicant id when uploading the document?

```java
onfido.document.upload(
  ...
  Document.request().applicantId(applicant.getId()).type(type)
);
```

Just in case you're not aware, by default we'll use the most recent document uploaded for an applicant for a document report, so most of the time you don't need to set `document_ids`.

**Comment by warrioru** [comment]
Hey @ciaran16 

Yes, I am setting the applicant id, but I do it when creating a Check.Request:

```
Check.Request requestCheck = Check.request();
      requestCheck
          .reportNames(new ArrayList<>(Arrays.asList("document", "facial_similarity_photo")))
          .applicantId(onfidoCheckObject.getApplicantId())
         .documentIds( Arrays.asList( onfidoCheckObject.getDocumentFrontId(),
       onfidoCheckObject.getDocumentBackId(), onfidoCheckObject.getFaceId()));
```

And yes, I was aware that's the default behaviour but we were not so sure if it's safe always to work with that logic. What if two persons create a check at the same?

Thanks for your prompt answer!

**Comment by ciaran16** [comment]
Hey @warrioru, you should be creating an applicant for every user/person, and therefore a different sdk token for each applicant. Assuming you're doing that, because we use the most recent document for a particular applicant, there's no risk of another person's document being used, even when creating checks at the same time.
