### ISSUE TITLE
privacyNoticesReadConsentGiven field does not correspond API

### ISSUE THREAD

**Issue by giylmi** [onfido/onfido-java#51]
From the doc: https://documentation.onfido.com/#create-check-request-body

**privacy_notices_read_consent_given**
> optional
Boolean to indicate that the privacy notices and terms of service have been read and, where specific laws require, that consent has been given for Onfido. This parameter should be set to true after gaining the necessary consent, and if it's set to false the request will fail with a validation error. If this parameter is omitted when creating the check, it will be returned as null in the check response object.

in code:
`@Json(name = "privacy_notices_read_consent_given") private final boolean privacyNoticesReadConsentGiven;`

This results in error
`com.squareup.moshi.JsonDataException: Expected a boolean but was NULL at path $.privacy_notices_read_consent_given`

**Comment by Phoebe-B** [comment]
This issue was fixed in the [v2.2.1 ](https://github.com/onfido/onfido-java/releases/tag/v2.2.1) release. Please upgrade to use v2.2.1 onwards. Closing this issue, but please don't hesitate to reach out if we can help further.
