### ISSUE TITLE
Empty string of LocalDate is not handled 

### ISSUE THREAD

**Issue by mkhairuddin** [onfido/onfido-java#57]
[https://documentation.onfido.com/#autofill-beta](https://documentation.onfido.com/#autofill-beta)

The auto fill api will return DateTimeParseException if the date of birth value is empty string.
`java.time.format.DateTimeParseException: Text '' could not be parsed at index 0 at $.extracted_data.date_of_birth`

In code:

> package com.onfido.api;
> ..
> public final class ApiJson<T> {
>   private static final class LocalDateAdapter {
>    ...
>     /**
>      * Converts a json string to a LocalDate.
>      *
>      * @param dateString the date string
>      * @return the local date
>      */
>     @FromJson
>     LocalDate fromJson(String dateString) {
>       return dateString == null ? null : LocalDate.parse(dateString);
>     }
>   }
 
 must check if the dateString is empty or null, then return null

**Comment by R4md4c** [comment]
Thank you for your contribution, very much appreciated! Just to keep you in the loop, before accepting your PR, we're asking the relevant team responsible for this API for input, to rule out any unexpected bugs from there side, especially knowing that the Auto-fill API is in beta.

**Comment by R4md4c** [comment]
Fixed in v2.3.1, thanks!
