### ISSUE TITLE
can we add support for autofill beta api

### ISSUE THREAD

**Issue by sourabhparsekar** [onfido/onfido-java#60]
Onfido Autofill Beta APIs gives OCR capabilities. Can we have them integrated.

**Comment by Phoebe-B** [comment]
Hi @sourabhparsekar, thank you for getting in touch. We do not currently have support to include beta APIs in our client libraries so unfortunately we can't add the Autofill OCR capabilities at the moment. However, we will discuss this internally to see how we handle beta APIs in our client libraries for the future.

**Comment by sourabhparsekar** [comment]
Thanks for the response @Phoebe-B. We were exploring beta APIs. For now we will directly consume them as REST API. Let us know if you add the support.
